import '@/styles/globals.css';

import type {LayoutRouteProps} from '@/lib/nextjs/nextjs.types';
import {interFont, jetBrainsMonoFont} from '@/styles/fonts';
import type {Metadata} from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: LayoutRouteProps) {
  return (
    <html lang="en">
      <body className={`${interFont.className} ${jetBrainsMonoFont.className} antialiased`}>{children}</body>
    </html>
  );
}
