import '@/styles/globals.css';

import type {LayoutRouteProps} from '@/lib/nextjs.types';
import type {Metadata} from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: LayoutRouteProps) {
  return (
    <html lang="en">
      <body className={'antialiased'}>{children}</body>
    </html>
  );
}
