name: Code quality and tests

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'develop'
  pull_request:
    branches:
      - '**'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Biome'
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: 'Run Biome'
        run: biome ci .

      - name: 'Install Bun'
        uses: oven-sh/setup-bun@v2

      #### Caching is currently disabled because builds are faster without it.
      #### Re-evaluate this when the project grows larger, as caching may improve performance with more dependencies. ####
#      - name: 'Cache Dependencies'
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.bun/install/cache
#          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile

      - name: 'Run TypeScript'
        run: npm run ts

      - name: 'Run tests'
        run: bun test